version: '3.8'

services:
  bible-api:
    # build: .
    image: edilsonss123/biblia-kj-api:1
    container_name: bible-api
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./src:/app
      - /app/node_modules
    restart: unless-stopped
